name: call_in_dart
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.0.1

dev_dependencies:
  lints: ^5.0.0
